### ISSUE TITLE
Get error while adding this package.

### ISSUE THREAD

**Issue by crapthings** [mkarliner/meteor-mosca#1]
meteor add mkarliner:mosca
 => Errors while adding packages:

While checking for mkarliner:mosca@0.0.4:
error: No compatible build found

**Comment by mkarliner** [comment]
\Which platform are you on? LInux32/64/OSX?

**Comment by mkarliner** [comment]
@crapthings Please try again - I've rebuilt for  OSX and Linux64

**Comment by crapthings** [comment]
osx 10.10.2, i'll try new push. thanks michael.

**Comment by crapthings** [comment]
0.0.4, just add it, work lke a charm~
