### ISSUE TITLE
No compatible binary build found for this package.

### ISSUE THREAD

**Issue by crapthings** [mkarliner/meteor-mosca#3]
I've got this while upgrade meteor.
But it is working fine for me.

**Comment by mkarliner** [comment]
Thanks. These binary packages are a real problem, there are now 4 separate builds to do for each one, manually, and no way to track them.

**Comment by jamesmacfie** [comment]
Is there a work around for this or any way for others to help out? Not entirely sure what "No compatible binary build found for this package" means yet so I don't know how to contribute.

**Comment by mkarliner** [comment]
It means I'm behind again. Because this package has to be built separately for every different platform, its a bit of a bind I sometimes forget to do. I have to get hold of a a login on OSX, linux32, linux64 and windows and build indivudually. Which one do you need?

**Comment by jamesmacfie** [comment]
I'm after the OSX build. Is there a way to do this myself and contribute back to your project or is it something you have to do?

**Comment by mkarliner** [comment]
I'll fix this today. However, I think you can just pull the github repo and do the publish-for-arch yourself.
Sorry for the delay. I've been travelling and not anywhere for long enough to do this for the last 24 hours.

**Comment by mkarliner** [comment]
Mac version published. Please tell me if you have any problems.

**Comment by jamesmacfie** [comment]
:+1: Thank you

**Comment by techside-it** [comment]
Same error on Ubuntu server 14.04 x64.
Can you solve for this platform ?

Thanks

**Comment by cuckoohello** [comment]
Could you provide x64 version?
Thank you!

**Comment by iascchen** [comment]
Could you provide Debian x64 version?
Thank you!

**Comment by mkarliner** [comment]
linux x64 version published.

techsideit, my appologies for not spotting this earlier.

Guys, want to tell me what your projects are?\
